id: P006947
initial_creation_type: ocr
source_metadata:
  id: bdr:W8027
  title: མངོན་པ་མཛོད་ཀྱི་འགྲེལ་ཆེན་གྲུབ་བདེའི་དཔྱིད་འཇོ
  author: ''
  volumes:
    ba309d346d844ed899f20df6b2d288fd:
      image_group_id: I4135
      title: ''
      volume_number: 1
      total_pages: 634
    f8e6349481d04ec0b533b55e21460cc7:
      image_group_id: I4136
      title: ''
      volume_number: 2
      total_pages: 828
ebook_metadata:
  title: མངོན་པ་མཛོད་ཀྱི་འགྲེལ་ཆེན་གྲུབ་བདེའི་དཔྱིད་འཇོ
  author: ''
  sku: P006947
  cover: cover.jpg
  layers:
  - pagination
