id: P006947
initial_creation_type: ocr
source_metadata:
  id: bdr:W8027
  title: མངོན་པ་མཛོད་ཀྱི་འགྲེལ་ཆེན་གྲུབ་བདེའི་དཔྱིད་འཇོ
  author: ''
  volumes:
    690bf08c61314c639a4b113b1de3352a:
      image_group_id: I4135
      title: ''
      volume_number: 1
      total_pages: 634
    74b86beef4c942c491d6c3b0410cc151:
      image_group_id: I4136
      title: ''
      volume_number: 2
      total_pages: 828
ebook_metadata:
  title: མངོན་པ་མཛོད་ཀྱི་འགྲེལ་ཆེན་གྲུབ་བདེའི་དཔྱིད་འཇོ
  author: ''
  sku: P006947
  cover: cover.jpg
  layers:
  - pagination
